version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:stable
    environment:
      EULA: "true"
      VERSION: 1.20.1
      TYPE: FORGE
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro

volumes:
  data:
